petstagram/common/urls.py
from django.urls import path, include

from petstagram.common import views
from petstagram.common.views import CommonView

urlpatterns = [
    path('', CommonView.as_view(), name='home'),
    # path('', views.common, name='home'),
    path('like/<int:photo_id>/', views.like_functionality, name='like'),
    path('share/<int:photo_id>/', views.copy_link_to_clipboard, name='share'),
    path('comment/<int:photo_id>/', views.add_comment, name='comment'),

]

petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('petstagram.common.urls')),
    path('accounts/', include('petstagram.accounts.urls')),
    path('pets/', include('petstagram.pets.urls')),
    path('photos/', include('petstagram.photos.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

petstagram/common/models.py
from django.db import models

from petstagram.photos.models import Photo


class Comment(models.Model):
    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE
    )

    text = models.TextField(max_length=300)

    datetime = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-datetime']


class Like(models.Model):
    to_photo = models.ForeignKey(
        to=Photo,
        on_delete=models.CASCADE
    )

petstagram/common/forms.py
from django import forms

from petstagram.common.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Add comment...'}),
        }


class SearchForm(forms.Form):
    pet_name = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search by pet name...'}
        )
    )

petstagram/common/views.py
from django.shortcuts import render, redirect, resolve_url
from django.views.generic import ListView
from pyperclip import copy
from django.core.paginator import Paginator

from petstagram.common.forms import CommentForm, SearchForm
from petstagram.common.models import Like
from petstagram.photos.models import Photo


class CommonView(ListView):
    model = Photo
    template_name = 'common/home-page.html'
    context_object_name = 'all_photos'
    paginate_by = 3


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['comment_form'] = CommentForm()
        context['search_form'] = SearchForm(self.request.GET)

        return context


    def get_queryset(self):
        queryset = super().get_queryset()
        pet_name = self.request.GET.get('pet_name')

        if pet_name:
            queryset = queryset.filter(tagged_pets__name__icontains=pet_name)

        return queryset


# def common(request):
#     all_photos = Photo.objects.all()
#     comment_form = CommentForm()
#     search_form = SearchForm(request.POST)
#
#     if search_form.is_valid():
#         all_photos = all_photos.filter(
#             tagged_pets__name__icontains=search_form.cleaned_data['pet_name']
#         )
#
#     photos_per_page = 2
#     paginator = Paginator(all_photos, photos_per_page)
#     page = request.GET.get('page')
#
#     all_photos = paginator.get_page(page)
#
#     context = {
#         'all_photos': all_photos,
#         'comment_form': comment_form,
#         'search_form': search_form,
#     }
#
#     return render(request, template_name='common/home-page.html', context=context)


def like_functionality(request, photo_id):
    photo = Photo.objects.get(id=photo_id)
    liked_objects = Like.objects.filter(to_photo=photo.id).first()

    if liked_objects:
        liked_objects.delete()
    else:
        liked_objects = Like(to_photo=photo)
        liked_objects.save()

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')


def copy_link_to_clipboard(request, photo_id):
    copy(request.META['HTTP_HOST'] + resolve_url('photo-details', photo_id))

    return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')


def add_comment(request, photo_id):
    if request.method == 'POST':
        photo = Photo.objects.get(id=photo_id)
        form  = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.to_photo = photo
            comment.save()

        return redirect(request.META['HTTP_REFERER'] + f'#{photo_id}')

templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <title>Petstagram</title>
</head>

<body>
    {% include 'common/nav.html' %}

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <div class="footer">
           <span class="footer-section">
              © 2024 SOFTUNI WORKSHOP FOR PYTHON WEB MODULE
           </span>
    </div>

</body>
</html>

templates/common/home-page.html
{% extends 'common/base.html' %}
{% load url_query_append %}
{% load static %}

{% block content %}
<div class="container">
    <div class="col-9">

        <form class="searchbar">
            {{search_form}}
            <button>
                <img src="/static/images/search.png" height="18" alt="img2">
            </button>
        </form>

        {% include 'common/pet-posts.html' %}

            <div class="pagination">
                <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                <span class="step-links-buttons">

                    <!-- If there are previous and next photos -->
                    {% if page_obj.has_previous and page_obj.has_next %}
                        <a href="?{% url_query_append_tag request 'page' page_obj.previous_page_number %}">
                            <i class="fa-solid fa-arrow-left"></i>
                        </a>
                        <a href="?{% url_query_append_tag request 'page' page_obj.next_page_number %}">
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>

                    <!-- If there are only previous photos -->
                    {% elif page_obj.has_previous %}
                        <a href="?{% url_query_append_tag request 'page' page_obj.previous_page_number %}">
                            <i class="fa-solid fa-arrow-left"></i>
                        </a>

                    <!-- If there are only next photos -->
                    {% elif page_obj.has_next %}
                        <a href="?{% url_query_append_tag request 'page' page_obj.next_page_number %}">
                            <i class="fa-solid fa-arrow-right"></i>
                        </a>
                    {% endif %}

                </span>
            </div>
     </div>
</div>

{% endblock %}

templates/common/nav.html
{% load static %}

<nav class="navbar">
        <div class="container">
            <div class="logo">
                <a href="#">
                    <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}"
                         alt="img1">
                </a>
                <a class="home" href="{% url 'home' %}">
                    <i>Petstagram</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group">
                    <li class="nav-item">
                        <a href="{% url 'add-pet' %}">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'add-photo' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login' %}">
                            <i>Login</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'register' %}">
                            <i>Register</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#">
                            <i>Logout</i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

templates/common/pet-posts.html
{% for photo in all_photos %}

<div class="card">
    <div class="top">
        <div class="userDetails">
            <!-- Link to User Profile Page -->
            <a href="#">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="/static/images/person.png" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <!-- Link to User Profile Page -->
                <a href="#">
                    <!-- if user has first name and last name -->
                    Diyan Kalaydzhiev
                    <!-- else -->
                    <!-- show user username -->
                </a>
                <br>
                <!-- if the photo has location -->
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}
            </h3>
        </div>
    </div>
    <!-- End User Details and Image Location -->

    <!-- Start Pet Photo -->
    <div class="imgBx" id="{{ photo.id }}">
        <img src="{{photo.photo.url}}" alt="post" class="cover">
    </div>
    <!-- End Pet Photo -->

    <!-- Start Like and Share Buttons -->
    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <!-- Start Like Button -->
                <span class="heart">
                    <a href="{% url 'like' photo.id %}">
                        {% if photo.like_set.all %}
                            <i class="fa-solid fa-heart" style="color: #ed4040;"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    </a>
                </span>
                <!-- End Like Button -->

                <!-- Start Share Button -->
                <a href="{% url 'share' photo.id %}">
                    <i class="fa-solid fa-share"></i>
                </a>
                <!-- End Share Button -->

            </div>
        </div>
        <!-- End Like and Share Buttons -->

        <!-- Number of Likes per Photo -->
        <p class="likes">{{ photo.like_set.count }}</p>


        <!-- Start Tagged Pets -->
        {% for pet in photo.tagged_pets.all %}
            <!-- Link to First Tagged Pet Details Page-->
            <a href="{% url 'pet-details' 'username' pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}
        <!-- End Tagged Pets -->

        <!-- Link to Photo Details Page -->
        {% if photo_page %}
            <p class="pet-details">{{ photo.description }}</p>
        {% else %}

        <a href="{% url 'photo-details' photo.pk %}">
            <h4 class="details">See details</h4>
        </a>
        {% endif %}

        <!-- Date of Publication -->
        <h5 class="postTime">{{photo.date_of_publication}}</h5>

        <!-- Start Add Comments Section -->
        <div class="addComments">

            <!-- Start Add Comments Form -->
            <form method="post" action="{% url 'comment' photo.id %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit">Post</button>
            </form>
            <!-- End Add Comments Form -->

        </div>
        <!-- End Add Comments Section -->

    </div>
</div>

{% endfor %}